package makroud

import lkb "github.com/ulule/loukoum/v3/builder"

// Query is a query generated by loukoum and makroud.
type Query struct {
	Raw   string
	Query string
	Args  []interface{}
}

// String returns query statement.
func (q Query) String() string {
	return q.Raw
}

// NewQuery creates a new Query instance from given loukoum builder.
func NewQuery(builder lkb.Builder) Query {
	raw := builder.String()
	query, args := builder.Query()
	return Query{
		Raw:   raw,
		Query: query,
		Args:  args,
	}
}

// NewRawQuery creates a new Query instance from given query.
func NewRawQuery(raw string) Query {
	return Query{
		Raw: raw,
	}
}
