#!/bin/bash

set -eo pipefail

if [[ ! -x "$(command -v go)" ]]; then
  echo >&2 "go runtime is required: https://golang.org/doc/install"
  echo >&2 "You can use scripts/go-wrapper $0 to use go in a docker container."
  exit 1
fi

SOURCE_DIRECTORY=$(dirname "${BASH_SOURCE[0]}")
cd "${SOURCE_DIRECTORY}/.."

do_analyze() {

    mkdir -p testdata
    go test -coverprofile=testdata/coverage.out ./...

}

do_view() {

    go tool cover -html=testdata/coverage.out

}


case "$1" in
    --view)
        do_view
    ;;
    --analyze)
        do_analyze
    ;;
    *)
        do_analyze
        do_view
    ;;
esac
exit 0
