#!/bin/bash

set -eo pipefail

golinter_path="${GOPATH}/bin/golangci-lint"
if [[ ! -x "${golinter_path}" ]]; then
    go get -u -v github.com/golangci/golangci-lint/cmd/golangci-lint
fi

SOURCE_DIRECTORY=$(dirname "${BASH_SOURCE[0]}")
cd "${SOURCE_DIRECTORY}/.."

OPTIONS=$(go list -f '{{.Dir}}' ./...)
if [ -n "$1" ]; then
    OPTIONS="$@"
fi

golangci-lint run ${OPTIONS}
