#!/bin/bash

SOURCE_DIRECTORY=$(dirname "${BASH_SOURCE[0]}")
cd "${SOURCE_DIRECTORY}/.."

scripts/database

gotest_path="${GOPATH}/src/github.com/stretchr/testify/require"

if [[ ! -x "${gotest_path}" ]]; then
    go get -d -u -v github.com/stretchr/testify/require
fi

OPTIONS="./..."
if [ -n "$1" ]; then
    OPTIONS="$@"
fi

go test -v -count=1 ${OPTIONS}
