#!/bin/bash

if [[ ! -x "$(command -v go)" ]]; then
  echo >&2 "go runtime is required: https://golang.org/doc/install"
  echo >&2 "You can use scripts/go-wrapper $0 to use go in a docker container."
  exit 1
fi

GOPATH=$(go env GOPATH)

SOURCE_DIRECTORY=$(dirname "${BASH_SOURCE[0]}")
cd "${SOURCE_DIRECTORY}/.."

if [ -z "$DB_SETUP" ]; then
    scripts/database || exit 253
fi

OPTIONS=$(go list -f '{{.Dir}}' ./...)
if [ -n "$1" ]; then
    OPTIONS="$@"
fi

go test -v -race -count=1 -parallel=1 ${OPTIONS}
