#!/bin/bash

SOURCE_DIRECTORY=$(dirname "${BASH_SOURCE[0]}")
cd "${SOURCE_DIRECTORY}/.."

if [ -z "$DB_SETUP" ]; then
    scripts/database || exit 253
fi

gotest_path="${GOPATH}/src/github.com/stretchr/testify/require"
if [[ ! -x "${gotest_path}" ]]; then
    go get -d -u -v github.com/stretchr/testify/require
fi

OPTIONS=$(go list -f '{{.Dir}}' ./... | grep -v 'github.com/ulule/makroud/benchmark')
if [ -n "$1" ]; then
    OPTIONS="$@"
fi

go test -v -race -count=1 -parallel=1 ${OPTIONS}
